/**
 * Copyright © 2023, School CRM Inc. ALL RIGHTS RESERVED.
 *
 * This software is the confidential information of School CRM Inc., and is licensed as
 * restricted rights software. The use,reproduction, or disclosure of this software is subject to
 * restrictions set forth in your license agreement with School CRM.
*/

export const ActionTypes = {
    AUTH_INFO: "AUTH_INFO",
    DISPLAY_TOAST: "DISPLAY_TOAST",
    MARKSHEET_CLASS: "MARKSHEET_CLASS",
    MARKSHEET_SECTION: "MARKSHEET_SECTION",
    MARKSHEET_STUDENTS: "MARKSHEET_STUDENTS",
    MENU_ITEM: "MENU_ITEM",
    SET_LISTING_AMENITIES: "SET_LISTING_AMENITIES",
    SET_All_AMENITIES: "SET_All_AMENITIES",
    SET_BUSES: "SET_BUSES",
    SET_All_CLASSES: "SET_All_CLASSES",
    SET_LISTING_CLASSES: "SET_LISTING_CLASSES",
    SET_SCHOOL_CLASSES: "SET_SCHOOL_CLASSES",
    SET_MARKSHEETS: "SET_MARKSHEETS",
    SET_All_SECTIONS: "SET_All_SECTIONS",
    SET_LISTING_SECTIONS: "SET_LISTING_SECTIONS",
    SET_SCHOOL_SECTIONS: "SET_SCHOOL_SECTIONS",
    SET_SCHOOLS: "SET_SCHOOLS",
    SET_SCHOOL_PERIODS: "SET_SCHOOL_PERIODS",
    SET_STUDENTS: "SET_STUDENTS",
    SET_LISTING_SUBJECTS: "SET_LISTING_SUBJECTS",
    SET_CLASS_SUBJECTS: "SET_CLASS_SUBJECTS",
    SET_ALL_SUBJECTS: "SET_ALL_SUBJECTS",
    SET_TEACHERS: "SET_TEACHERS",
    SET_USERS: "SET_USERS",
    SET_EMPLOYEES: "SET_EMPLOYEES",
    SET_HOLIDAYS: "SET_HOLIDAYS",
    SET_PAYMENTS: "SET_PAYMENTS",
    SET_USER_ROLES: "SET_USER_ROLES",
    REGISTER_USER: "REGISTER_USER"
};
